# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-11 20:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopMovies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Rank', models.IntegerField(default=-1)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('poster', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('year', models.IntegerField(default=-1)),
                ('genre', models.CharField(max_length=200)),
                ('Awards', models.CharField(max_length=200)),
                ('imdbRating', models.FloatField(default=-1)),
                ('gross_revenue', models.FloatField(default=-1)),
            ],
        ),
    ]
