# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-12 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_auto_20161111_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='topmovies',
            name='Actors',
            field=models.CharField(default='Fei Wang', max_length=200),
        ),
        migrations.AddField(
            model_name='topmovies',
            name='Director',
            field=models.CharField(default='Fei Wang', max_length=200),
        ),
        migrations.AddField(
            model_name='topmovies',
            name='Plot',
            field=models.CharField(default='Fei Wang\\s story', max_length=500),
        ),
    ]
